<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0"
  xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>..\_Include;$(SolutionDir)_Build\$(Configuration)\Lib_Import\;..\_RanSDK\BugTrap;..\_RanSDK\DirectX\Include;..\_RanSDK\ZLib\Source;..\_RanSDK\OggVorbis\Include;..\_RanSDK\LZO\lzo\include;..\_RanSDK\LZO\lzo;..\_RanSDK\Boost;..\_RanSDK\LuaPlus\Source;..\_RanSDK\LuaPlus\Source\src;..\_RanSDK\libcpuid\libcpuid;..\_RanSDK\HackShield\Include;..\_RanSDK\CV\Include\C;..\_RanSDK\ETC\Include\;..\_RanSDK\Freetype\Include\;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>_CRT_NONSTDC_NO_DEPRECATE;_CRT_SECURE_NO_DEPRECATE;_CRT_NONSTDC_NO_WARNINGS;_SECURE_SCL=0;_SECURE_ATL=0;_HAS_ITERATOR_DEBUGGING=0;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalOptions>/Zm200 %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>